### ISSUE TITLE
Natija chiqqanda uning joylashishi

### ISSUE THREAD

**Issue by omon490** [gog19/CurrencyChange#1]
Uzbek kronasiga valyutani exchange qilganda sakrab ketayapti va buttonni nisbatan o'rta keltirib qo'yilsa yanada chiroyliroq bo'lar edi))
![image](https://user-images.githubusercontent.com/71442262/101671950-08e9ee80-3a77-11eb-8e64-bf6d87f2e88e.png)

**Comment by gog19** [comment]
Hal qilamiz.

**Comment by gog19** [comment]
ok
